name: flutter_video_thumbnail
description: "Flutter get video thumbnail"
repository: https://github.com/vanvixi/flutter_video_thumbnail/tree/main/flutter_video_thumbnail
homepage: https://github.com/vanvixi/flutter_video_thumbnail

version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      default_package: flutter_video_thumbnail_android
#      ios:
#        default_package: flutter_video_thumbnail_darwin


dependencies:
  flutter:
    sdk: flutter
  flutter_video_thumbnail_platform_interface:
    git:
      url: https://github.com/vanvixi/flutter_video_thumbnail.git
      path: flutter_video_thumbnail_platform_interface
      ref: main

  flutter_video_thumbnail_android:
    git:
      url: https://github.com/vanvixi/flutter_video_thumbnail.git
      path: flutter_video_thumbnail_android
      ref: main

#  flutter_video_thumbnail_darwin:
#    git:
#      url: https://github.com/vanvixi/flutter_video_thumbnail.git
#      path: flutter_video_thumbnail_darwin
#      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0