name: flutter_video_thumbnail_platform_interface
description: "A common platform interface for the flutter_video_thumbnail plugin"
repository: https://github.com/vanvixi/flutter_video_thumbnail/tree/main/flutter_video_thumbnail_platform_interface
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - video
  - video-thumbnail
